#!/bin/bash

set -e

if (( $# < 2 )); then
    echo "Usage: ./compile <target file> <source files>..."
    exit 1
fi

outfile="$1"
srcfiles="${@:2}"

CFLAGS=${CFLAGS:-}

LLVM_PREFIX=${LLVM_ROOT:+$LLVM_ROOT/}

${LLVM_PREFIX}clang \
    --target=wasm32-unknown-unknown-wasm \
    -o $outfile \
    -nostartfiles \
    -Wl,--no-entry,--demangle,--allow-undefined-file=src/external.syms \
    $CFLAGS \
    -- $srcfiles
